### ISSUE TITLE
Italics

### ISSUE THREAD

**Issue by weijia-cheng** [lukasbystricky/henry-james_the-ambassadors#2]
I see that you've applied em tags to various words that were probably italicized in the original text because they were being treated as French or other foreign language words:

- cul-de-sac
- difficile
- salle-à-manger
- porte-cochère
- banlieue
- carriole
- auberge
- bock
- agrément
- milieu
- parti
- atelier
- fait accompli
- panem et circenses
- hotels
- femme(s) du monde
- boiseries
- sabots
- jeune fille
- (less sure on this one) nuance

Per [8.2.9.4](https://standardebooks.org/manual/1.6.2/8-typography#8.2.9.4) we should not be italicizing "naturalized" English words like these unless they are genuinely emphasized. My impression from skimming over the relevant passages quickly was that these words were not really being emphasized. I would suggest reading the passages again to assess whether they are actually emphasized, and remove the `<em>` tag whenever they are not. We don't need to have our italics exactly match the printed version's italics.

I don't know if "bon" should be marked as emphasis on `src/epub/text/chapter-2-1.xhtml:137`. It looks like this is the French word meaning "good" and though apparently "bon" is an English word, there's no usage in Merriam-Webster that corresponds to that sense. I would mark this up as a French word. It actually looks like you marked "bon" as a French word elsewhere, too.

"consommation" on `src/epub/text/chapter-2-2.xhtml:22` should be marked as a French word too, it's not even in Merriam-Webster.

`src/epub/text/chapter-9-3.xhtml:12:` `<i epub:type="se:name.publication.book">Maîtres 
d’Autrefois</i>` should also have an xml:lang attribute, so `<i epub:type="se:name.publication.book" xml:lang="fr">Maîtres 
d’Autrefois</i>`

**Comment by lukasbystricky** [comment]
I left italics on certain words:
- difficile
- milieu
- parti
- fait accompli
- panem et circenses
- femmes du monde 
- jeune fille
